const users = [
  ["kim", "김군"],
  ["lee", "이군"],
  ["park", "박군"],
  ["jeong", "정양"],
  ["oh", "오양"],
  ["kwon", "권양"],
  ["yoon", "윤군"],
  ["sim", "심양"],
  ["han", "한군"],
  ["ahn", "안양"],
  ["yim", "임양"],
  ["hong", "홍군"]
];

const feeds = [
  ["비행기 안", "airplane.jpg", "airplane_t.jpg", "여행,비행기,휴가,해외"],
  ["대나무숲", "bamboo.jpg", "bamboo_t.jpg", "여행,담양,휴가,지방"],
  ["생일", "bday.jpg", "bday_t.jpg", "친구,생일,약속,케이크"],
  ["바닷가", "beach.jpg", "beach_t.jpg", "여행,바닷가,휴가,연인"],
  ["맥주", "beer.png", "beer_t.png", "약속,친구,맥주,술"],
  ["술병", "bottles.jpg", "bottles_t.jpg", "약속,친구,맥주,술"],
  ["에어컨 고장", "broken_airconditioner.jpg", "broken_airconditioner_t.jpg", "집,에어컨수리,집콕,지각"],
  ["엘리베이터 고장", "broken_elevator.jpg", "broken_elevatort_t.jpg", "엘리베이터고장,지각,사고"],
  ["불멍", "campfire.jpg", "campfire_t.jpg", "여행,캠핑,휴가,불멍"],
  ["캠핑", "camping.jpg", "camping_t.jpg", "여행,캠핑,휴가,바베큐"],
  ["여행2", "trip2.jpg", "trip2_t.jpg", "여행,친구,지방,가족"],
  ["결혼식", "wedding.jpg", "wedding_t.jpg", "결혼식,친구,가족,일정"],
  ["냥이들", "cats.jpg", "cats_t.jpg", "집사,집콕,고양이"],
  ["대부도", "daebudo.jpg", "daebudo_t.jpg", "대부도,여행,휴가,가족"],
  ["데이트", "date.jpg", "date_t.jpg", "데이트,전시,연인,친구"],
  ["강아지 산책", "dog_walking.jpg", "dog_walking_t.jpg", "강아지산책,한강,강아지,가족"],
  ["개 산책", "dog_walking2.jpg", "dog_walking2_t.jpg", "강아지산책,강아지,가족,연인"],
  ["강쥐들", "dogs.jpg", "dogs_t.jpg", "강아지,친구,가족"],
  ["퐁듀", "eatout.jpg", "eatout_t.jpg", "외식,친구,가족,약속"],
  ["시험", "exam.jpeg", "exam_t.jpeg", "자격증시험,스케줄,시험"],
  ["실험", "experiment.jpg", "experiment_t.jpg", "학교,실험실,교수님"],
  ["화재인것 같지만 소독차", "fake_fire.jpg", "fake_fire_t.jpg", "화재,교통,사고"],
  ["꽃구경", "flowers.jpg", "flowers_t.jpg", "꽃구경,선약,친구,데이트"],
  ["친구집", "friends_home.jpg", "friends_home_t.jpg", "약속,친구집,집들이,모임"],
  ["퇴근길 지하철", "full_subway.jpg", "full_subway_t.jpg", "지하철,퇴근,출근,지각"],
  ["고기", "gogi2.jpg", "gogi2_t.jpg", "약속,고기,친구,회식,모임"],
  ["소고기", "gogi.jpg", "gogi_t.jpg", "선약,고기,친구,회식,모임"],
  ["경주", "gyeongju.jpg", "gyeongju_t.jpg", "경주,여행,가족,친구"],
  ["미용실", "hair_salon.jpg", "hair_salon_t.jpg", "미용실,스케줄,선약"],
  ["홈파티", "happy.jpg", "happy_t.jpg", "집들이,생일,친구,축하"],
  ["자가격리", "home.png", "home_t.png", "자가격리,코로나,집콕"],
  ["편백찜", "homeparty.jpg", "homeparty_t.jpg", "집들이,친구,음식,파티,모임"],
  ["병원밥", "hospital_meal.jpg", "hospital_meal_t.jpg", "병원,입원,환자"],
  ["병원", "hospital.jpg", "hospital_t.jpg", "병원,입원,환자"],
  ["호캉스", "hotel.jpg", "hotel_t.jpg", "호캉스,휴가,여행"],
  ["제주도", "jeju.jpg", "jeju_t.jpg", "제주도,여행,휴가"],
  ["연구실", "labs.jpg", "labs_t.jpg", "실험실,교수님,학교,과제"],
  ["런던", "london.jpg", "london_t.jpg", "런던,여행,휴가,친구"],
  ["어무니", "mom.jpg", "mom_t.jpg", "엄마,외출,가족,약속"],
  ["등산", "mountain.jpg", "mountain_t.jpg", "등산,운동,약속,외출"],
  ["야근", "night_shift.jpg", "night_shift_t.jpg", "야근,회사,바빠"],
  ["피크닉", "picnic.jpg", "picnic_t.jpg", "피크닉,외출,친구,선약"],
  ["사당역 버스줄", "sadang_station.jpg", "sadang_station_t.jpg", "퇴근,출근,지각,회사"],
  ["해산물", "seafood.jpg", "seafood_t.jpg", "가족,외식,맛집,해물"],
  ["딱새우", "shrimp.jpg", "shrimp_t.jpg", "딱새우,외식,친구,데이트"],
  ["보드", "skateboard.jpg", "skateboard_t.jpg", "운동,취미,보드,친구"],
  ["폭설", "heavy_snow.jpg", "heavy_snow_t.jpg", "눈,폭설,교통"],
  ["장염", "stomachache.jpg", "stomachache_t.jpg", "죽,장염,아파,환자"],
  ["타이어 펑크", "tire.png", "tire_t.png", "타이어펑크,사고,지각"],
  ["여행", "trip.jpg", "trip_t.jpg", "남이섬,외출,친구,가족"],
];

const comments = [
  "오늘 진짜 집에 가고 싶은데 선배가 술먹자고 해서 썼습니다 ㅠㅠㅠ 👍 👍",
  "주말에 집 밖에서 안나갈 핑계를 생각하다가 오게 됐어요..ㅎㅎ 신박하네요 핑계마켓 자주 이용하겠습니다!",
  "오 이거 자연스럽네요!!! 잘 쓸게요",
  "와 이사진 선배한테 보냈다가 어디냐고 물어봐서 당황했는데 다행히 잘 넘어갔어요… 휴",
  "선약있다고 하고 이사진 보냈더니 어디냐고 물어봐서 당황했네여... 위치도 태그해주시면 좋을 것 같아요 !!",
  "진짜 같아서 좋아요",
  "퍼가요~❤️ 거절 못하는 저에게 그저 빛...",
  "잘 쓰겠습니다!",
  "오 이거닷 잘쓸게용",
  "오늘은 이걸로 간다....",
  "굿굿굿 무난하고 딱이에요~~~",
  "ㅋㅋㅋㅋㅋㅋㅋ리얼하네요",
  "이거다! 가져갑니당 ㄱㅅㄱㅅ",
  "저 딱 이상황인데 사진이 없어서 썼어요ㅠㅋㅋ 감삼다",
  "질척질척 선배 짜증짜증 핑계 마켓은 사랑입니다 💚",
  "친구야 미안하다 쉬고싶다.... 🤥",
  "유용하게 썼습니다! 최고최고",
  "아싸 라스트팡 가져갈게요 핑닭 하이 ! !",
  "까비..... 늦었네요 ㅠㅠ",
  "여기 어딘지 아시는 분 있나요??",
]

const dummy = {
  users,
  feeds,
  comments
}

module.exports = dummy;